import { web, mobile, backend, creator } from "../assets";

import { baskey, foot, chess, TT } from "../assets/eventsicons";

const services = [
  {
    title: "Web Developer",
    icon: web,
  },
  {
    title: "React Native Developer",
    icon: mobile,
  },
  {
    title: "Backend Developer",
    icon: backend,
  },
  {
    title: "Content Creator",
    icon: creator,
  },
];

const events = [
  {
    id: "1",
    title: "Athletics",
    icon: web,
    category: " M / W",
    team: "solo",
    registerPath: "/create",
  },
  {
    id: "2",
    title: "Badminton",
    icon: web,
    category: " M / W",
    team: "solo",
    registerPath: "/create",
  },
  {
    id: "3",
    title: "Basketball",
    icon: web,
    category: " M / W",
    team: "team",
    registerPath: "/create",
  },
  {
    id: "4",
    title: "Cricket",
    icon: web,
    category: " M / W",
    team: "team",
    registerPath: "/create",
  },
  {
    id: "5",
    title: "Football",
    icon: web,
    category: " M / W",
    team: "team",
    registerPath: "/create",
  },
  {
    id: "6",
    title: "Table Tennis",
    icon: web,
    category: " M / W",
    team: "Doubles / Mixed",
    registerPath: "/create",
  },
  {
    id: "7",
    title: "Lawn Tennis",
    icon: web,
    category: " M / W",
    team: "doubles / mixed",
    registerPath: "/create",
  },
  {
    id: "8",
    title: "Volleyball",
    icon: web,
    category: " M / W",
    team: "team",
    registerPath: "/create",
  },
  {
    id: "9",
    title: "Kabaddi",
    icon: web,
    category: " M / W",
    team: "team",
    registerPath: "/create",
  },
  {
    id: "10",
    title: "Hockey",
    icon: web,
    category: " M / W",
    team: "team",
    registerPath: "/create",
  },
  {
    id: "11",
    title: "Squash",
    icon: web,
    category: " M / W",
    team: "team",
    registerPath: "/create",
  },
  {
    id: "12",
    title: "Chess",
    icon: web,
    category: " M / W",
    team: "team",
    registerPath: "/create",
  },
  {
    id: "13",
    title: "BGMI",
    icon: web,
    category: " M / W",
    team: "team",
    registerPath: "/create",
  },
  {
    id: "14",
    title: "Valorant",
    icon: web,
    category: " M / W",
    team: "team",
    registerPath: "/create",
  },
  {
    id: "15",
    title: "Clash Royale",
    icon: web,
    category: " M / W",
    team: "team",
    registerPath: "/create",
  },
];

const signupFields = [
  {
    labelText: "Email address",
    labelFor: "email",
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "First Name",
    labelFor: "First Name",
    id: "first_name",
    name: "First Name",
    type: "text",
    autoComplete: "First Name",
    isRequired: true,
    placeholder: "First Name",
  },
  {
    labelText: "Last Name",
    labelFor: "Last Name",
    id: "last_name",
    name: "Last Name",
    type: "text",
    autoComplete: "Last Name",
    isRequired: true,
    placeholder: " Last Name",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
  {
    labelText: "gender",
    labelFor: "gender",
    id: "gender",
    name: "gender",
    type: "dropdown",
    autoComplete: "",
    isRequired: true,
    placeholder: "Gender",
    options: [
      { value: "male", label: "Male" },
      { value: "female", label: "Female" },
    ],
  },
  {
    labelText: "Phone",
    labelFor: "phone",
    id: "phone",
    name: "phone",
    type: "tel",
    autoComplete: "",
    isRequired: true,
    placeholder: "+91 xxxxxxxxxx",
  },
  {
    labelText: "college",
    labelFor: "college",
    id: "college",
    name: "college",
    type: "text",
    autoComplete: "college",
    isRequired: true,
    placeholder: "College",
  },
  {
    labelText: "State",
    labelFor: "state",
    id: "state",
    name: "state",
    type: "text",
    autoComplete: "state",
    isRequired: true,
    placeholder: "State",
  },
  {
    labelText: "accomodation_required",
    labelFor: "accomodation_required",
    id: "accomodation_required",
    name: "accomodation_required",
    type: "dropdown",
    autoComplete: "",
    isRequired: true,
    placeholder: "Accomadation",
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
    ],
  },
  
];

const loginFields = [
  {
    labelText: "Email address",
    labelFor: "email-address",
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];

export const eventOptions = [
  {
    value: '1',
    label: 'Athletics',
    category: ['men','women'],
    teamTypes: ['100m', '200m', '400m', '800m', '1500m', '5000m'],
  },
  {
    value: '2',
    label: 'Badminton',
    category: ['men','women','mixed'],
    teamTypes: ['Team'],
  },
  {
    value: '3',
    label: 'Basketball',
    category: ['men','women'],
    teamTypes: ['Team'],
  },
  {
    value: '4',
    label: 'Cricket',
    category: 'men',
    teamTypes: ['Team'],
  },
  {
    value: '5',
    label: 'Football',
    category: ['men','women'],
    teamTypes: ['Team'],
  },
  {
    value: '6',
    label: 'Table Tennis',
    category: ['men','women'],
    teamTypes: ['Team'],
  },
  {
    value: '7',
    label: 'Lawn Tennis',
    category: 'men',
    teamTypes: ['Team'],
  },
  {
    value: '8',
    label: 'Volleyball',
    category: ['men','women'],
    teamTypes: ['Team'],
  },
  {
    value: '9',
    label: 'Kabaddi',
    category: 'men',
    teamTypes: ['Team'],
  },
  {
    value: '10',
    label: 'Hockey',
    category: 'men',
    teamTypes: ['Team'],
  },
  {
    value: '11',
    label: 'Squash',
    category: 'men',
    teamTypes: ['Single'],
  },
  {
    value: '12',
    label: 'Chess',
    category: 'open',
    teamTypes: ['Single'],
  },
  {
    value: '13',
    label: 'BGMI',
    category: 'open',
    teamTypes: ['Team'],
  },
  {
    value: '14',
    label: 'Valorant',
    category: 'open',
    teamTypes: ['Team'],
  },
  {
    value: '15',
    label: 'Clash Royale',
    category: 'open',
    teamTypes: ['Team'],
  },
  // Add more events here
];


export const categoryOptions = ['men', 'women', 'mixed', 'open'];
export const teamTypeOptions = ['100m', '200m', '400m', '800m', '1500m', '5000m','Team', 'Single'];

export { services, events, signupFields, loginFields};
