import { web, mobile, backend, creator, Cricket, Football, Athletics, Badminton, Basketball, TableTennis, LawnTennis, VolleyBall, Kabaddi, Hockey, Squash, BGMI, Valo, ClashRoyale } from "../assets";

import {
  ankit,
  aryan,
  aradhya,
  ashish,
  balaji,
  bhanu,
  divyanshu,
  harsh,
  hima,
  jatin,
  jesika,
  karan,
  pranav,
  pratap,
  rachit,
  rajat,
  rajkumar,
  rohit,
  sahil,
  saurabh,
  shivangi,
  shobhit,
  sumit,
  swapnil,
  tushar,
  utkarshs,
  utkarshgupta,
  vijay,
  vishal,
  khetan,
  jason,
  harendra,} from "../assets/team"

import { chess } from "../assets";

export const Teamdata = [
  {
    title : "1",
    imgPath : "",
    Name : "Navneet Meena",
    Designation : "Festival Chief",
    instaLink : "https://www.instagram.com/_navneet_meena_/",
  },
  {
    title : "2",
    imgPath : harendra,
    Name : "Harendra Pal",
    Designation : "Festival Chief",
    instaLink : "https://www.instagram.com/tomarharendrapal__up80_/",
  },
  {
    title : "3",
    imgPath : aryan,
    Name : "Aryan Jain",
    Designation : "Festival Chief",
    instaLink : "https://www.instagram.com/whatisthisaryan/",
  },
  {
    title : "4",
    imgPath : khetan,
    Name : "Ketan Tomar",
    Designation : "Festival Chief",
    instaLink : "",
  },
  {
    title : "23",
    imgPath : aradhya,
    Name : "Dr. Aradhya Giri",
    Designation : "Public Relations",
    instaLink : "https://www.instagram.com/ara_dhyagiri/?hl=en",
  },
  {
    title : "24",
    imgPath : shivangi,
    Name : "Shivangi Garg",
    Designation : "Public Relations",
    instaLink : "https://instagram.com/shivangigarg00?igshid=MzMyNGUyNmU2YQ==",
  },
  {
    title : "25",
    imgPath : harsh,
    Name : "Harsh Vardhan",
    Designation : "Public Relations",
    instaLink : "https://instagram.com/_hvk__27_?igshid=MzRlODBiNWFlZA==",
  },
  {
    title : "26",
    imgPath : utkarshgupta,
    Name : "Utkarsh Gupta",
    Designation : "Public Relations",
    instaLink : "https://instagram.com/utkarshgupta__07?igshid=OGQ5ZDc2ODk2ZA==",
  },
  {
    title : "7",
    imgPath : karan,
    Name : "Karan Shisode",
    Designation : "Sports",
    instaLink : "https://www.instagram.com/admiral.karan/",
  },
  {
    title : "8",
    imgPath : rachit,
    Name : "Rachit Kataria",
    Designation : "Sports",
    instaLink : "https://instagram.com/rachitkatxria?igshid=NzZlODBkYWE4Ng==",
  },
  {
    title : "9",
    imgPath : saurabh,
    Name : "Saurabh",
    Designation : "Sports",
    instaLink : "https://www.instagram.com/meenakumarsaurabh/",
  },
  {
    title : "10",
    imgPath : balaji,
    Name : "Balaji Kharte",
    Designation : "Sports",
    instaLink : "https://instagram.com/khartebalaji9575?igshid=OGQ5ZDc2ODk2ZA==",
  },
  {
    title : "6",
    imgPath : pranav,
    Name : "Pranav Kumar",
    Designation : "Design & Creativity",
    instaLink : "https://www.instagram.com/pel_synergy/",
  },
  {
    title : "5",
    imgPath : jesika,
    Name : "Jesika Rai",
    Designation : "Design & Creativity",
    instaLink : "https://www.instagram.com/jesika_rai_/",
  },
  {
    title : "32",
    imgPath : jason,
    Name : "Jason Daniel",
    Designation : "Web Development",
    instaLink : "https://www.instagram.com/jason_dan_iel/",
  },
  {
    title : "33",
    imgPath : "akarsh",
    Name : "Akarsh",
    Designation : "Web Development",
    instaLink : "https://www.instagram.com/",
  },
  
  {
    title : "11",
    imgPath : rohit,
    Name : "Rohit Nair",
    Designation : "Marketing",
    instaLink : "https://instagram.com/rohit__1398?igshid=MzMyNGUyNmU2YQ==",
  },
  {
    title : "12",
    imgPath : divyanshu,
    Name : "Divyanshu Singhal",
    Designation : "Marketing",
    instaLink : "https://instagram.com/divyanshu.singhal29?igshid=MzRlODBiNWFlZA==",
  },
  {
    title : "13",
    imgPath : jatin,
    Name : "Jatin Kumar",
    Designation : "Marketing",
    instaLink : "https://www.instagram.com/i_m_jatink5/",
  },
  {
    title : "14",
    imgPath : tushar,
    Name : "Tushar Mehta",
    Designation : "Marketing",
    instaLink : "https://instagram.com/tusharm.ehta?igshid=OGQ5ZDc2ODk2ZA==",
  },
  {
    title : "15",
    imgPath : rajat,
    Name : "Rajat Jindal",
    Designation : "Publicity & Media",
    instaLink : "https://instagram.com/eudaimonic__life?igshid=MzMyNGUyNmU2YQ==",
  },
  {
    title : "16",
    imgPath : ashish,
    Name : "Ashish Meena",
    Designation : "Publicity & Media",
    instaLink : "https://www.instagram.com/aashish______/",
  },
  {
    title : "17",
    imgPath : sumit,
    Name : "Sumit Kumar",
    Designation : "Publicity & Media",
    instaLink : "https://www.instagram.com/ruminative_soul_",
  },
  {
    title : "18",
    imgPath : utkarshs,
    Name : "Utkarsh Srivastava",
    Designation : "Publicity & Media",
    instaLink : "https://www.instagram.com/utkarsh__srivastav_/",
  },
  {
    title : "19",
    imgPath : shobhit,
    Name : "Shobhit Singh",
    Designation : "ATS",
    instaLink : "https://www.instagram.com/thakur_shobhitsingh_chouhan/",
  },
  {
    title : "20",
    imgPath : sahil,
    Name : "Sahil Bohra ",
    Designation : "ATS",
    instaLink : "https://instagram.com/bohrasahil81?igshid=OGQ5ZDc2ODk2ZA==",
  },
  {
    title : "21",
    imgPath : vijay,
    Name : "Vijay Anand",
    Designation : "ATS",
    instaLink : "#",
  },
  {
    title : "22",
    imgPath : hima,
    Name : "Hima Varshitha Nandi",
    Designation : "ATS",
    instaLink : "https://instagram.com/hima_varshi.02?utm_source=qr&igshid=MThlNWY1MzQwNA==",
  },
  
  {
    title : "27",
    imgPath : swapnil,
    Name : "Swapnil Shimpi ",
    Designation : "Informals",
    instaLink : "https://instagram.com/swapverse?igshid=NzZlODBkYWE4Ng==",
  },
  {
    title : "28",
    imgPath : rajkumar,
    Name : "Rajkumar Mina ",
    Designation : "Informals",
    instaLink : "https://instagram.com/rajkumar_meena28?igshid=OGQ5ZDc2ODk2ZA==",
  },
  {
    title : "29",
    imgPath : vishal,
    Name : "Vishal Jharwal",
    Designation : "Informals",
    instaLink : "https://instagram.com/vishal.jharwal?igshid=MzRlODBiNWFlZA==",
  },
  {
    title : "30",
    imgPath : ankit,
    Name : "Ankit Meena",
    Designation : "Resources",
    instaLink : "https://www.instagram.com/Ankit.meena_18/ ",
  },
  {
    title : "31",
    imgPath : bhanu,
    Name : "Bhanu Pratap Singh",
    Designation : "Resources",
    instaLink : "https://instagram.com/pratap_mandovra?igshid=OGQ5ZDc2ODk2ZA==",
  },

];

const events = [
  {
    id: "1",
    title: "Athletics",
    icon: Athletics,
    category: " M / W",
    team: "solo",
    registerPath: "/create",
  },
  {
    id: "2",
    title: "Badminton",
    icon: Badminton,
    category: " M / W",
    team: "solo",
    registerPath: "/create",
  },
  {
    id: "3",
    title: "Basketball",
    icon: Basketball,
    category: " M / W",
    team: "team",
    registerPath: "/create",
  },
  {
    id: "4",
    title: "Cricket",
    icon: Cricket,
    category: " M / W",
    team: "team",
    registerPath: "/create",
  },
  {
    id: "5",
    title: "Football",
    icon: Football,
    category: " M / W",
    team: "team",
    registerPath: "/create",
  },
  {
    id: "6",
    title: "Table Tennis",
    icon: TableTennis,
    category: " M / W",
    team: "Doubles / Mixed",
    registerPath: "/create",
  },
  {
    id: "7",
    title: "Lawn Tennis",
    icon: LawnTennis,
    category: " M / W",
    team: "doubles / mixed",
    registerPath: "/create",
  },
  {
    id: "8",
    title: "Volleyball",
    icon: VolleyBall,
    category: " M / W",
    team: "team",
    registerPath: "/create",
  },
  {
    id: "9",
    title: "Kabaddi",
    icon: Kabaddi,
    category: " M / W",
    team: "team",
    registerPath: "/create",
  },
  {
    id: "10",
    title: "Hockey",
    icon: Hockey,
    category: " M / W",
    team: "team",
    registerPath: "/create",
  },
  {
    id: "11",
    title: "Squash",
    icon: Squash,
    category: " M / W",
    team: "team",
    registerPath: "/create",
  },
  {
    id: "12",
    title: "Chess",
    icon: chess,
    category: " M / W",
    team: "team",
    registerPath: "/create",
  },
  {
    id: "13",
    title: "BGMI",
    icon: BGMI,
    category: " M / W",
    team: "team",
    registerPath: "/create",
  },
  {
    id: "14",
    title: "Valorant",
    icon: Valo,
    category: " M / W",
    team: "team",
    registerPath: "/create",
  },
  {
    id: "15",
    title: "Clash Royale",
    icon: ClashRoyale,
    category: " M / W",
    team: "team",
    registerPath: "/create",
  },
];

const signupFields = [
  {
    labelText: "Email address",
    labelFor: "email",
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "First Name",
    labelFor: "First Name",
    id: "first_name",
    name: "First Name",
    type: "text",
    autoComplete: "First Name",
    isRequired: true,
    placeholder: "First Name",
  },
  {
    labelText: "Last Name",
    labelFor: "Last Name",
    id: "last_name",
    name: "Last Name",
    type: "text",
    autoComplete: "Last Name",
    isRequired: true,
    placeholder: " Last Name",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
  {
    labelText: "Confirm Password",
    labelFor: "cnfpassword",
    id: "confirm_password",
    name: "cnfpassword",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Confirm Password",
  },
  {
    labelText: "gender",
    labelFor: "gender",
    id: "gender",
    name: "gender",
    type: "dropdown",
    autoComplete: "",
    isRequired: true,
    placeholder: "Gender",
    options: [
      { value: "M", label: "Male" },
      { value: "F", label: "Female" },
      { value: "T", label: "Other" },
    ],
  },
  {
    labelText: "Phone",
    labelFor: "phone",
    id: "phone",
    name: "phone",
    type: "tel",
    autoComplete: "",
    isRequired: true,
    placeholder: "+91 xxxxxxxxxx",
  },
  {
    labelText: "college",
    labelFor: "college",
    id: "college",
    name: "college",
    type: "text",
    autoComplete: "college",
    isRequired: true,
    placeholder: "College",
  },
  {
    labelText: "State",
    labelFor: "state",
    id: "state",
    name: "state",
    type: "dropdown",
    options : [
        { value : '1', label : 'Andhra Pradesh'},
        { value : '2', label : 'Arunachal Pradesh'},
        { value : '3', label : 'Assam'},
        { value : '4', label : 'Bihar'},
        { value : '5', label : 'Chhattisgarh'},
        { value : '6', label : 'Goa'},
        { value : '7', label : 'Gujarat'},
        { value : '8', label : 'Haryana'},
        { value : '9', label : 'Himachal Pradesh'},
        { value : '10', label : 'Jammu & Kashmir'},
        { value : '11', label : 'Jharkhand'},
        { value : '12', label : 'Karnataka'},
        { value : '13', label : 'Kerala'},
        { value : '14', label : 'Madhya Pradesh'},
        { value : '15', label : 'Maharashtra'},
        { value : '16', label : 'Manipur'},
        { value : '17', label : 'Meghalaya'},
        { value : '18', label : 'Mizoram'},
        { value : '19', label : 'Nagaland'},
        { value : '20', label : 'Odisha'},
        { value : '21', label : 'Punjab'},
        { value : '22', label : 'Rajasthan'},
        { value : '23', label : 'Sikkim'},
        { value : '24', label : 'Tamil Nadu'},
        { value : '25', label : 'Telangana'},
        { value : '26', label : 'Tripura'},
        { value : '27', label : 'Uttarakhand'},
        { value : '28', label : 'Uttar Pradesh'},
        { value : '29', label : 'West Bengal'},
        { value : '30', label : 'Andaman & Nicobar Islands'},
        { value : '31', label : 'Delhi'},
        { value : '32', label : 'Chandigarh'},
        { value : '33', label : 'Dadra & Naagar Haveli'},
        { value : '34', label : 'Daman & Diu'},
        { value : '35', label : 'Lakshadweep'},
        { value : '36', label : 'Puducherry'},
    ],
    autoComplete: "state",
    isRequired: true,
    placeholder: "State",
  },
  {
    labelText: "accomodation_required",
    labelFor: "accomodation_required",
    id: "accommodation_required",
    name: "accomodation_required",
    type: "dropdown",
    autoComplete: "",
    isRequired: true,
    placeholder: "Accomadation",
    options: [
      { value: "Y", label: "Yes" },
      { value: "N", label: "No" },
    ],
  },

];

const loginFields = [
  {
    labelText: "Email address",
    labelFor: "email-address",
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
];

export const eventOptions = [
  {
    value: '1',
    label: 'Athletics',
    category: ['men', 'women'],
    teamTypes: ['100m', '200m', '400m', '800m', '1500m', '5000m', '4x100m', '4x400m'],
  },
  {
    value: '2',
    label: 'Badminton',
    category: ['men', 'women', 'mixed'],
    teamTypes: ['Team'],
  },
  {
    value: '3',
    label: 'Basketball',
    category: ['men', 'women'],
    teamTypes: ['Team'],
  },
  {
    value: '4',
    label: 'Cricket',
    category: 'men',
    teamTypes: ['Team'],
  },
  {
    value: '5',
    label: 'Football',
    category: ['men', 'women'],
    teamTypes: ['Team'],
  },
  {
    value: '6',
    label: 'Table Tennis',
    category: ['men', 'women'],
    teamTypes: ['Team'],
  },
  {
    value: '7',
    label: 'Lawn Tennis',
    category: 'men',
    teamTypes: ['Team'],
  },
  {
    value: '8',
    label: 'Volleyball',
    category: ['men', 'women'],
    teamTypes: ['Team'],
  },
  {
    value: '9',
    label: 'Kabaddi',
    category: 'men',
    teamTypes: ['Team'],
  },
  {
    value: '10',
    label: 'Hockey',
    category: 'men',
    teamTypes: ['Team'],
  },
  {
    value: '11',
    label: 'Squash',
    category: 'men',
    teamTypes: ['Single'],
  },
  {
    value: '12',
    label: 'Chess',
    category: 'open',
    teamTypes: ['Single'],
  },
  {
    value: '13',
    label: 'BGMI',
    category: 'open',
    teamTypes: ['Team'],
  },
  {
    value: '14',
    label: 'Valorant',
    category: 'open',
    teamTypes: ['Team'],
  },
  {
    value: '15',
    label: 'Clash Royale',
    category: 'open',
    teamTypes: ['Team'],
  },
];

export const categoryOptions = ['men', 'women', 'mixed', 'open'];
export const teamTypeOptions = ['100m', '200m', '400m', '800m', '1500m', '5000m', '4x100m', '4x400m', 'Team', 'Single'];

export {events, signupFields, loginFields };
